force-app/main/default/objects/NSWCPPPayment__c/NSWCPPPayment__c.object-meta.xml
<CustomObject>
    <label>NSW CPP Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSW CPP Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NSWCPPPayment__c/fields/AccountToken__c.field-meta.xml
<CustomField>
    <fullName>AccountToken__c</fullName>
    <label>Account Token</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/PaymentCompletionReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentCompletionReference__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Payment Completion Reference</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NSWCPPPaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/PaymentReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentReference__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NSWCPPPaymentStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/NSWCPPPaymentStep__c.object-meta.xml
<CustomObject>
    <label>NSW CPP Payment Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSW CPP Payment Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/AccountToken__c.field-meta.xml
<CustomField>
    <fullName>AccountToken__c</fullName>
    <label>Account Token</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/BankReference__c.field-meta.xml
<CustomField>
    <fullName>BankReference__c</fullName>
    <label>Bank Reference</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/BPayBillerCode__c.field-meta.xml
<CustomField>
    <fullName>BPayBillerCode__c</fullName>
    <label>BPay Biller Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/BPayCRN__c.field-meta.xml
<CustomField>
    <fullName>BPayCRN__c</fullName>
    <label>BPay CRN</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/BPayProcessingDate__c.field-meta.xml
<CustomField>
    <fullName>BPayProcessingDate__c</fullName>
    <label>BPay Processing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/CardLast4Digits__c.field-meta.xml
<CustomField>
    <fullName>CardLast4Digits__c</fullName>
    <label>Card Last 4 Digits</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/CardPresent__c.field-meta.xml
<CustomField>
    <fullName>CardPresent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Card Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/CardType__c.field-meta.xml
<CustomField>
    <fullName>CardType__c</fullName>
    <label>Card Type</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <label>EmailAddress</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>NSWCPPPayment__c</referenceTo>
    <relationshipLabel>Steps</relationshipLabel>
    <relationshipName>PaymentSteps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/PaymentCompletionReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentCompletionReference__c</fullName>
    <label>Payment Completion Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NSWCPPPaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/PaymentReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentReference__c</fullName>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NSWCPPPaymentStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Surcharge__c</fullName>
    <label>Surcharge</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/SurchargeAbsorbed__c.field-meta.xml
<CustomField>
    <fullName>SurchargeAbsorbed__c</fullName>
    <label>Surcharge Absorbed</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/SurchargeGST__c.field-meta.xml
<CustomField>
    <fullName>SurchargeGST__c</fullName>
    <label>Surcharge GST</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/recordTypes/Completed.recordType-meta.xml
<RecordType>
    <fullName>Completed</fullName>
    <active>true</active>
    <label>Completed</label>
</RecordType>

force-app/main/default/objects/NSWCPPPaymentStep__c/recordTypes/Pending.recordType-meta.xml
<RecordType>
    <fullName>Pending</fullName>
    <active>true</active>
    <label>Pending</label>
</RecordType>

force-app/main/default/globalValueSets/NSWCPPPaymentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BPAY</fullName>
        <label>BPay</label>
    </customValue>
    <customValue>
        <fullName>CARD</fullName>
        <label>Card</label>
    </customValue>
    <customValue>
        <fullName>PAYID</fullName>
        <label>PayID</label>
    </customValue>
    <customValue>
        <fullName>PAYPAL</fullName>
        <label>PayPal</label>
    </customValue>
    <masterLabel>NSW CPP Payment Method</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NSWCPPPaymentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initiated</fullName>
        <default>true</default>
        <label>Initiated</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <masterLabel>NSW CPP Payment Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NSWCPPOperationComplete.cls
/**
 * @description Complete a payment as a result of a back-end callback service call from NSW CPP
 *              as per step D in the sequence diagram: grab public key, verify JWS signature,
 *              match with the pending payment in the database and persist a step.
 * @see NSWCPPServicePaymentCompletion
 * @author E. Schweitzer
 */

/* TODO: Security Review by Paul Lucas
    The following would be executed by the guest user
    as a continuation of the Apex Rest service NSWCPPServicePaymentCompletion 
    The guest user cannot be granted any user access rights anyway.
    This is a narrow-band, very controlled operation.
*/

@SuppressWarnings('PMD.ApexCRUDViolation, PMD.AvoidGlobalModifier')
global without sharing class NSWCPPOperationComplete {
    final static String SETTINGS_CATEGORY_COMPLETION = 'Completion';
    final static String SETTINGS_PUBLICKEY = 'PublicKey';
    final static String CLAIM_CARD = 'card';
    final static String CLAIM_BPAY = 'bPay';

    /**
      * @description public point of entry for this class, sequences all the steps
      *              required to register a payment completion: grab NSW CPP public key,
      *              validate the JWS signature and invoke the database part.
      * @param compactJWS signed JWT provided by NSW CPP as part of the payment callback
      * @return Id of the persisted NSWCPPPaymentStep__c
      * @throws NoPublicKeyException when the public key cannot be found in settings
      * @throws InvalidJWSException when the JWS does not add up
      * @throws UnmatchedPaymentRefException if the completed payment cannot be matched to 
      *               a pending payment based on the payment reference
      */
    public static Id completePayment(String compactJWS) {
        Map<String, String> settings = NSWCPPSettings.getSettingsMapForCategory(SETTINGS_CATEGORY_COMPLETION);
        String publicKey = NSWCPPSettings.getSettingFromMap(SETTINGS_PUBLICKEY, settings);

        if (publicKey == null) {
            throw new NoPublicKeyException('Could not find ' + SETTINGS_PUBLICKEY + ' in settings.');
        }

        Auth.JWT verifiedJWS;
        
        try {
            verifiedJWS = Auth.JWTUtil.validateJWTWithKey(compactJWS, publicKey);
        } catch (Auth.JWTValidationException e) {
            throw new InvalidJWSException('JWS does not have a valid signature.');
        }

        return completePayment(verifiedJWS);
    } 

    /**
      * @description persist details of the payment using claims packaged in the JWT:
      *              grab additional card or bPay object claims, match with a pending
      *              payment record based on the payment reference and persist a 
      *              NSWCPPPaymentStep__c record with all details for auditability.
      *              JWT payload is persisted for technical auditability but would not
      *              necessarily have to be once accelerator matures or if data volumes
      *              become a concern.
      * @param jwt the payload of the verified JWS
      * @return the recordId of the persisted NSWCPPPaymentStep__c 
      * @throws UnmatchedPaymentRefException if the payment reference could not be matched
      */
    @TestVisible
    private static Id completePayment(Auth.JWT jwt) {
        Id cpsRecordTypeId = NSWCPPOperation.getRecordTypeIdByName(NSWCPPOperation.STATUS_COMPLETED);
        Map<String, Object> claims = jwt.getAdditionalClaims();

        /*
         * deal with a bug in JWT class which does not deserialize claims when they're objects 
         */

        Object card = claims.get(CLAIM_CARD);
        if (card instanceof String) {
            claims.put(CLAIM_CARD, JSON.deserializeUntyped((String) card));
        }

        Object bPay = claims.get(CLAIM_BPAY);
        if (bPay instanceof String) {
            claims.put(CLAIM_BPAY, JSON.deserializeUntyped((String) bPay));
        }

        /* End */

        Map<String, Object> bPayMap = (Map<String, Object>) claims.get(CLAIM_BPAY);
        Map<String, Object> cardMap = (Map<String, Object>)claims.get(CLAIM_CARD);

        String paymentReference = String.valueOf(claims.get('paymentReference'));

        List<NSWCPPPayment__c> cpList = [
            SELECT Id, PaymentReference__c
            FROM NSWCPPPayment__c
            WHERE PaymentReference__c = :paymentReference 
                AND Status__c = :NSWCPPOperation.STATUS_PENDING
            LIMIT 1
            FOR UPDATE
        ];

        if (cpList.size() == 0) {
            // TODO: place in an exception queue of some sort vs throwing an exception -- current idea, invoke a flow whose details are parameterised so that the Accelerator user can decide how those exceptions get handled (e.g. case)
            throw new UnmatchedPaymentRefException();
        }

        NSWCPPPayment__c cp = cpList[0];

        cp.AccountToken__c = String.valueOf(claims.get('accountToken'));
        cp.PaymentCompletionReference__c = String.valueOf(claims.get('paymentCompletionReference'));
        cp.PaymentMethod__c = String.valueOf(claims.get('paymentMethod'));
        cp.PaymentReference__c = paymentReference;
        cp.Status__c = NSWCPPOperation.STATUS_COMPLETED;

        NSWCPPPaymentStep__c step = new NSWCPPPaymentStep__c(
            Name = NSWCPPOperation.STATUS_COMPLETED,
            Payment__c = cp.Id,
            RecordTypeId = cpsRecordTypeId,
            AccountToken__c = String.valueOf(claims.get('accountToken')),
            Amount__c = (Decimal) claims.get('amount'),
            BankReference__c = String.valueOf(claims.get('bankReference')),
            BPayBillerCode__c = bPayMap != null ? String.valueOf(bPayMap.get('billerCode')) : null,
            BPayCRN__c = bPayMap != null ? String.valueOf(bPayMap.get('crn')) : null,
            BPayProcessingDate__c = bPayMap != null ? Date.valueOf(bPayMap.get('processingDate')) : null,
            CardLast4Digits__c = cardMap != null ? String.valueOf(cardMap.get('last4Digits')) : null,
            CardPresent__c = cardMap != null ? Boolean.valueOf(cardMap.get('cardPresent')) : null,
            CardType__c = cardMap != null ? String.valueOf(cardMap.get('cardType')) : null,
            EmailAddress__c = String.valueOf(claims.get('emailAddress')),
            PaymentCompletionReference__c = String.valueOf(claims.get('paymentCompletionReference')),
            PaymentMethod__c = String.valueOf(claims.get('paymentMethod')),
            PaymentReference__c = paymentReference,
            Surcharge__c = (Decimal) claims.get('surcharge'),
            SurchargeAbsorbed__c = (Decimal) claims.get('absorbedSurcharge'),
            SurchargeGST__c = (Decimal) claims.get('surchargeGST'),
            Status__c = NSWCPPOperation.STATUS_COMPLETED,
            Type__c = NSWCPPOperation.TYPE_PAYMENT,
            Payload__c = jwt.toJSONString()
        );


        insert step;
        update cp;

        return cp.Id;
    }

    public class NoPublicKeyException extends Exception {}
    public class InvalidJWSException extends Exception {}
    public class UnmatchedPaymentRefException extends Exception {}
}