force-app/main/default/objects/NSWCPPPayment__c/NSWCPPPayment__c.object-meta.xml
<CustomObject>
    <label>NSW CPP Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSW CPP Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NSWCPPPayment__c/fields/AccountToken__c.field-meta.xml
<CustomField>
    <fullName>AccountToken__c</fullName>
    <label>Account Token</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/AgencyTransactionID__c.field-meta.xml
<CustomField>
    <fullName>AgencyTransactionID__c</fullName>
    <label>Agency Transaction ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/AmountPaid__c.field-meta.xml
<CustomField>
    <fullName>AmountPaid__c</fullName>
    <label>Amount Paid</label>
    <summarizedField>NSWCPPPaymentStep__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>NSWCPPPaymentStep__c.Status__c</field>
        <operation>equals</operation>
        <value>Completed</value>
    </summaryFilterItems>
    <summaryForeignKey>NSWCPPPaymentStep__c.Payment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>Amount__c -  AmountPaid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/PaymentCompletionReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentCompletionReference__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Payment Completion Reference</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NSWCPPPaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/PaymentReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentReference__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/ProductDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductDescription__c</fullName>
    <label>Product Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NSWCPPPayment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NSWCPPPaymentStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/NSWCPPPaymentStep__c.object-meta.xml
<CustomObject>
    <label>NSW CPP Payment Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSW CPP Payment Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/AccountToken__c.field-meta.xml
<CustomField>
    <fullName>AccountToken__c</fullName>
    <label>Account Token</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/AgencyTransactionID__c.field-meta.xml
<CustomField>
    <fullName>AgencyTransactionID__c</fullName>
    <label>Agency Transaction ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/BankReference__c.field-meta.xml
<CustomField>
    <fullName>BankReference__c</fullName>
    <label>Bank Reference</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/BPayBillerCode__c.field-meta.xml
<CustomField>
    <fullName>BPayBillerCode__c</fullName>
    <label>BPay Biller Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/BPayCRN__c.field-meta.xml
<CustomField>
    <fullName>BPayCRN__c</fullName>
    <label>BPay CRN</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/BPayProcessingDate__c.field-meta.xml
<CustomField>
    <fullName>BPayProcessingDate__c</fullName>
    <label>BPay Processing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/CardLast4Digits__c.field-meta.xml
<CustomField>
    <fullName>CardLast4Digits__c</fullName>
    <label>Card Last 4 Digits</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/CardPresent__c.field-meta.xml
<CustomField>
    <fullName>CardPresent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Card Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/CardType__c.field-meta.xml
<CustomField>
    <fullName>CardType__c</fullName>
    <label>Card Type</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <label>EmailAddress</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/PaymentCompletionReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentCompletionReference__c</fullName>
    <label>Payment Completion Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NSWCPPPaymentMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/PaymentReference__c.field-meta.xml
<CustomField>
    <fullName>PaymentReference__c</fullName>
    <label>Payment Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/ProductDescription__c.field-meta.xml
<CustomField>
    <fullName>ProductDescription__c</fullName>
    <label>Product Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NSWCPPPaymentStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Surcharge__c</fullName>
    <label>Surcharge</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/SurchargeAbsorbed__c.field-meta.xml
<CustomField>
    <fullName>SurchargeAbsorbed__c</fullName>
    <label>Surcharge Absorbed</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/fields/SurchargeGST__c.field-meta.xml
<CustomField>
    <fullName>SurchargeGST__c</fullName>
    <label>Surcharge GST</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NSWCPPPaymentStep__c/recordTypes/Completed.recordType-meta.xml
<RecordType>
    <fullName>Completed</fullName>
    <active>true</active>
    <label>Completed</label>
</RecordType>

force-app/main/default/globalValueSets/NSWCPPPaymentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BPAY</fullName>
        <label>BPay</label>
    </customValue>
    <customValue>
        <fullName>CARD</fullName>
        <label>Card</label>
    </customValue>
    <customValue>
        <fullName>PAYID</fullName>
        <label>PayID</label>
    </customValue>
    <customValue>
        <fullName>PAYPAL</fullName>
        <label>PayPal</label>
    </customValue>
    <masterLabel>NSW CPP Payment Method</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NSWCPPPaymentStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initiated</fullName>
        <default>true</default>
        <label>Initiated</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <masterLabel>NSW CPP Payment Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NSWCPPOperationComplete_Test.cls
@isTest
private class NSWCPPOperationComplete_Test {
    static final Map<String, Object> receivedRaw = new Map<String, Object> {
        'absorbedSurcharge' => 0.0, 
        'agencyTransactionId' => 'ceca3ef6-a1d0-4eb5-af84-a06a06d4df5c',
        'amount' => 33.0, 
        'bankReference' => '1123851865',
        'card' => new Map<String, Object> {
            'cardType' => 'VISA',
            'last4Digits' => '6459',
            'cardPresent' => false
        },
        'paymentCompletionReference' => 'YWVZ64HY9J', 
        'paymentMethod' => 'CARD',
        'paymentReference' => 'GPP-DIG-UvYd96GzRlu-_J-pOto3kg',
        'surcharge' => 0.13,
        'surchargeGST' =>  0.01
    };

    static final String COMPACT_JWS = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIyMTgyMzkwMjIsIm5hbWUiOiJUb21hc3ogWndpZXJ6Y2hvxYQifQ.t3VhQ7QsILDuV_HNFSMI-Fb2FoT7fuzalpS5AH8A9c0';

    static void logPaymentStep(NSWCPPPaymentStep__c value) {
        System.debug('> logPaymentStep');
        System.debug('  AccountToken__c: ' + value.AccountToken__c);
        System.debug('  AgencyTransactionID__c: ' + value.AgencyTransactionID__c);
        System.debug('  Amount__c: ' + value.Amount__c);
        System.debug('  BankReference__c: ' + value.BankReference__c);
        System.debug('  BPayBillerCode__c: ' + value.BPayBillerCode__c);
        System.debug('  BPayCRN__c: ' + value.BPayCRN__c);
        System.debug('  BPayProcessingDate__c: ' + value.BPayProcessingDate__c);
        System.debug('  CardLast4Digits__c: ' + value.CardLast4Digits__c);
        System.debug('  CardPresent__c: ' + value.CardPresent__c);
        System.debug('  CardType__c: ' + value.CardType__c);
        System.debug('  EmailAddress__c: ' + value.EmailAddress__c);
        System.debug('  PaymentCompletionReference__c: ' + value.PaymentCompletionReference__c);
        System.debug('  PaymentMethod__c: ' + value.PaymentMethod__c);
        System.debug('  PaymentReference__c: ' + value.PaymentReference__c);
        System.debug('  Surcharge__c: ' + value.Surcharge__c);
        System.debug('  SurchargeAbsorbed__c: ' + value.SurchargeAbsorbed__c);
        System.debug('  SurchargeGST__c: ' + value.SurchargeGST__c);
    }

    /* Cannot compare AgencyTransactionIds as it's not available for all steps/operations */
    static boolean compare(NSWCPPPaymentStep__c expected, 
                           NSWCPPPaymentStep__c received) {
        logPaymentStep(expected);
        logPaymentStep(received);
        return expected.AccountToken__c == received.AccountToken__c &&
               expected.Amount__c == received.Amount__c &&
               expected.BankReference__c == received.BankReference__c &&
               expected.BPayBillerCode__c == received.BPayBillerCode__c &&
               expected.BPayCRN__c == received.BPayCRN__c &&
               expected.BPayProcessingDate__c == received.BPayProcessingDate__c &&
               expected.CardLast4Digits__c == received.CardLast4Digits__c &&
               expected.CardPresent__c == received.CardPresent__c &&
        	   expected.CardType__c == received.CardType__c &&
               expected.EmailAddress__c == received.EmailAddress__c &&
               expected.PaymentCompletionReference__c == received.PaymentCompletionReference__c &&
        	   expected.PaymentMethod__c == received.PaymentMethod__c &&
               expected.PaymentReference__c == received.PaymentReference__c &&
               expected.Surcharge__c == received.Surcharge__c &&
               expected.SurchargeAbsorbed__c == received.SurchargeAbsorbed__c &&
               expected.SurchargeGST__c == received.SurchargeGST__c;
    }
    
    @isTest
    static void itProcessesAValidCardPaymentCompletion() {
        Auth.JWT jwt = new Auth.JWT();
        jwt.setSub((String) receivedRaw.get('paymentReference'));
        jwt.setAdditionalClaims(receivedRaw);

        NSWCPPPaymentStep__c expected = new NSWCPPPaymentStep__c(
            SurchargeAbsorbed__c = 0.0, 
            AccountToken__c = null,
            AgencyTransactionID__c = 'ceca3ef6-a1d0-4eb5-af84-a06a06d4df5c',
            Amount__c = 33.0, 
            BankReference__c = '1123851865',
            CardType__c = 'VISA',
            CardLast4Digits__c = '6459',
            CardPresent__c = false,
            EmailAddress__c = null,
            PaymentCompletionReference__c = 'YWVZ64HY9J', 
            PaymentMethod__c = 'CARD',
            PaymentReference__c = 'GPP-DIG-UvYd96GzRlu-_J-pOto3kg',
            Surcharge__c = 0.13,
            SurchargeGST__c = 0.01
        );

        Test.startTest();

        NSWCPPPayment__c initialPayment = new NSWCPPPayment__c(
            AgencyTransactionID__c = 'ceca3ef6-a1d0-4eb5-af84-a06a06d4df5c',
            Amount__c = 33.0,
            PaymentReference__c = 'GPP-DIG-UvYd96GzRlu-_J-pOto3kg',
            ProductDescription__c = 'Paintball venue licence',
            Status__c = NSWCPPOperation.STATUS_PENDING
        );

        insert initialPayment;

        NSWCPPOperationComplete.completePayment(jwt);

        NSWCPPPayment__c updatedPayment = [
            SELECT Id, AmountPaid__c, Balance__c, Status__c 
            FROM NSWCPPPayment__c
            WHERE Id = :initialPayment.Id
        ];

        List<NSWCPPPaymentStep__c> paymentSteps = [
            SELECT Id, AccountToken__c, AgencyTransactionID__c, Amount__c, BankReference__c, 
                BPayBillerCode__c, BPayCRN__c, BPayProcessingDate__c,
                CardType__c, CardLast4Digits__c, CardPresent__c, 
                EmailAddress__c, PaymentCompletionReference__c, PaymentMethod__c, PaymentReference__c,
                Surcharge__c, SurchargeAbsorbed__c, SurchargeGST__c, Status__c, RecordType.Name
            FROM NSWCPPPaymentStep__c
        ];

        Test.stopTest();

        System.assertEquals(
            NSWCPPOperation.STATUS_COMPLETED, 
            updatedPayment.Status__c, 
            'Payment should have completed.');
            
        System.assertEquals(
            0.0, 
            updatedPayment.Balance__c, 
            'Balance should be zero.');

        System.assertEquals(
            1, 
            paymentSteps.size(), 
            'There should be only one payment step');

        NSWCPPPaymentStep__c ps = paymentSteps[0];
        Boolean comparison = compare(ps, expected);

        System.assertEquals(
            NSWCPPOperation.STATUS_COMPLETED, 
            ps.Status__c, 
            'Payment step should have \'Completed\' status.');

        System.assertEquals(
            NSWCPPOperation.STATUS_COMPLETED, 
            ps.RecordType.Name, 
            'Payment step should have \'Completed\' record type.');

        System.assertEquals(
            true, 
            comparison, 
            'Payment step should have all field values from jwt mapped correctly.');
    }

    @isTest
    static void itThrowsAnExceptionForUnmatchedPayments() {
        Auth.JWT jwt = new Auth.JWT();
        jwt.setSub((String) receivedRaw.get('paymentReference'));
        jwt.setAdditionalClaims(receivedRaw);

        Boolean exceptionThrown = false;
        Test.startTest();

        try {
            NSWCPPOperationComplete.completePayment(jwt);
        } catch(NSWCPPOperationComplete.UnmatchedPaymentRefException e) {
            exceptionThrown = true;
        }

        Test.stopTest();

        System.assertEquals(
            true,
            exceptionThrown,
            'UnmatchedPaymentException should be thrown for unmatched payments');
    }

    @isTest
    static void itThrowsAnExceptionWhenJWSDoesNotAddUp() {
        Boolean exceptionThrown = false;

        Test.startTest();

        try {
            NSWCPPOperationComplete.completePayment(COMPACT_JWS);
        } catch (NSWCPPOperationComplete.InvalidJWSException e) {
            exceptionThrown = true;
        }

        Test.stopTest();

        System.assertEquals(
            true,
            exceptionThrown,
            'InvalidJWSException should be thrown when JWS does not add up');
    }

}